-- Mining.
--
-- Asteroid belts were generated by the system builder and then used for
-- nothing: they weighted NPC traffic and were never drawn, never collided
-- with and never mined. The Mining Laser was on sale at 8600 credits, the
-- projectile it fired was tagged `mining` and no code ever read the tag, and
-- the miner NPC behaviour began by checking a field that was never assigned.
-- This module is the missing end of that chain.
--
-- Rocks are placed the way points of interest are: deterministically, on a
-- coarse lattice, built only near the player and never stored. What *is*
-- stored is damage -- a rock you have chipped stays chipped for the session,
-- keyed by its lattice cell, so a belt does not silently refill while you are
-- working it.

local Rng = require("src.lib.rng")
local util = require("src.lib.util")

local mining = {}

local floor, sqrt = math.floor, math.sqrt

-- Rocks sit on a lattice this big; a belt a few hundred thousand km across
-- therefore holds thousands of them without any of them existing until you
-- are close enough to shoot at.
mining.CELL = 900
mining.VIEW_CELLS = 3

--- What a rock can contain, and how likely.
mining.ORES = {
    { id = "ore",        weight = 52, yield = { 2, 6 } },
    { id = "minerals",   weight = 30, yield = { 1, 4 } },
    { id = "raremetals", weight = 13, yield = { 1, 2 } },
    { id = "gems",       weight = 5,  yield = { 1, 1 } },
}

local function pickOre(rng)
    local total = 0
    for _, o in ipairs(mining.ORES) do total = total + o.weight end
    local r = rng:float() * total
    for _, o in ipairs(mining.ORES) do
        r = r - o.weight
        if r <= 0 then return o end
    end
    return mining.ORES[1]
end

-- ---------------------------------------------------------------------------
-- Placement
-- ---------------------------------------------------------------------------

--- Is this point inside one of the system's belts, and if so which?
function mining.beltAt(sys, x, y, z)
    if not sys.belts then return nil end
    local r = sqrt(x * x + z * z)
    for _, belt in ipairs(sys.belts) do
        if math.abs(r - belt.radius) < belt.width * 0.5
            and math.abs(y) < belt.thickness * 0.5 then
            return belt
        end
    end
    return nil
end

local function cellKey(cx, cy, cz)
    return cx .. "," .. cy .. "," .. cz
end

--- The rock in a lattice cell, or nil.
--
-- `damage` carries the session's chipping, so the caller passes the table it
-- keeps; nothing is written here that is not already in it.
function mining.rockAt(sys, belt, cx, cy, cz, damage)
    local seed = Rng.hash(belt.seed, cx, cy, cz)
    local rng = Rng.new(seed, "rock")
    -- density thins the field out; a sparse belt is mostly empty cells
    if rng:float() > belt.density * 0.55 then return nil end

    local cell = mining.CELL
    local x = (cx + rng:float()) * cell
    local y = (cy + rng:float()) * cell
    local z = (cz + rng:float()) * cell

    -- keep it inside the belt's torus rather than its bounding box
    local r = sqrt(x * x + z * z)
    if math.abs(r - belt.radius) > belt.width * 0.5 then return nil end
    if math.abs(y) > belt.thickness * 0.5 then return nil end

    local ore = pickOre(rng)
    local size = rng:range(28, 190)
    local key = cellKey(cx, cy, cz)
    local hp = size * 0.9 * (1 + belt.richness)
    return {
        key = key,
        x = x, y = y, z = z,
        radius = size,
        seed = seed,
        variant = rng:int(1, 5),
        spin = rng:range(-0.25, 0.25),
        phase = rng:float() * math.pi * 2,
        ore = ore.id,
        yield = rng:int(ore.yield[1], ore.yield[2]) + floor(belt.richness * 2),
        maxHealth = hp,
        health = hp - (damage and damage[key] or 0),
    }
end

--- Every rock near a point. Returns an array; empty when outside a belt.
function mining.near(sys, x, y, z, damage, out)
    out = out or {}
    for i = #out, 1, -1 do out[i] = nil end
    local belt = mining.beltAt(sys, x, y, z)
    if not belt then return out, nil end

    local cell = mining.CELL
    local n = mining.VIEW_CELLS
    local bx, by, bz = floor(x / cell), floor(y / cell), floor(z / cell)
    for dx = -n, n do
        for dy = -1, 1 do
            for dz = -n, n do
                local rock = mining.rockAt(sys, belt, bx + dx, by + dy, bz + dz, damage)
                if rock and rock.health > 0 then out[#out + 1] = rock end
            end
        end
    end
    return out, belt
end

-- ---------------------------------------------------------------------------
-- Extraction
-- ---------------------------------------------------------------------------

--- Applies a mining hit. Returns the ore id and tonnes freed, or nil.
--
-- Ore is released in proportion to the damage done, so a weak laser on a big
-- rock still pays -- just slowly. The rock is exhausted when its health runs
-- out, and the damage table remembers that for the rest of the session.
function mining.hit(rock, amount, damage)
    if not rock or rock.health <= 0 then return nil end
    local dealt = math.min(amount, rock.health)
    rock.health = rock.health - dealt
    damage[rock.key] = (damage[rock.key] or 0) + dealt

    local fraction = dealt / math.max(rock.maxHealth, 1)
    local tonnes = fraction * rock.yield
    -- accumulate fractional tonnes so small hits are not rounded away
    rock.pending = (rock.pending or 0) + tonnes
    local whole = floor(rock.pending)
    if whole < 1 then return nil end
    rock.pending = rock.pending - whole
    return rock.ore, whole
end

--- True when the rock has nothing left to give.
function mining.exhausted(rock) return rock.health <= 0 end

return mining
